export const toolbarTextsRu = {
  bold: 'Жирный',
  fontFamily: 'Шрифт',
  ai: 'AI генерация текста',
  fontSize: 'Размер шрифта',
  italic: 'Курсив',
  underline: 'Подчеркнутый',
  highlight: 'Цвет выделения',
  strikethrough: 'Зачеркнутый',
  color: 'Цвет текста',
  search: 'Поиск',
  link: 'Ссылка',
  image: 'Изображение',
  table: 'Вставить таблицу',
  tableActions: 'Настройки таблицы',
  addRowBefore: 'Вставить строку выше',
  addRowAfter: 'Вставить строку ниже',
  addColumnBefore: 'Вставить столбец слева',
  addColumnAfter: 'Вставить столбец справа',
  deleteRow: 'Удалить строку',
  deleteColumn: 'Удалить столбец',
  deleteTable: 'Удалить таблицу',
  removeBorders: 'Убрать границы',
  mergeCells: 'Объединить ячейки',
  splitCell: 'Разделить ячейку',
  fixTables: 'Исправить таблицы',
  textAlign: 'Выравнивание',
  bulletList: 'Маркированный список',
  numberedList: 'Нумерованный список',
  indentLeft: 'Уменьшить отступ',
  indentRight: 'Увеличить отступ',
  zoom: 'Масштаб',
  undo: 'Отменить',
  redo: 'Повторить',
  trackChanges: 'Отслеживание изменений',
  trackChangesAccept: 'Принять изменения в выделенном',
  trackChangesReject: 'Отклонить изменения в выделенном',
  trackChangesOriginal: 'Показать оригинал',
  trackChangesFinal: 'Показать финал',
  clearFormatting: 'Очистить форматирование',
  copyFormat: 'Копировать форматирование',
  lineHeight: 'Межстрочный интервал',
  formatText: 'Форматирование текста',
  ruler: 'Показать или скрыть линейку',
  pageBreak: 'Вставить разрыв страницы',
  documentEditingMode: 'Редактирование',
  documentSuggestingMode: 'Предложение',
  documentViewingMode: 'Просмотр',
  documentEditingModeDescription: 'Редактировать документ напрямую',
  documentSuggestingModeDescription: 'Правки становятся предложениями',
  documentViewingModeDescription: 'Просмотр чистовой версии документа',
  linkedStyles: 'Связанные стили',
};
